apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-prediction-service
  namespace: default
  labels:
    app: ml-prediction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-prediction-service
  template:
    metadata:
      labels:
        app: ml-prediction-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ml-prediction-service
          image: ghadabannourii/smartsite-ml-prediction-service:11
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
              ephemeral-storage: "256Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ml-prediction-service
  namespace: default
spec:
  selector:
    app: ml-prediction-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30800
  type: NodePort
