import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

@Schema({ timestamps: true })
export class Alert extends Document {
  @Prop({ required: true })
  siteId: string;

  @Prop({ required: true })
  type: 'high-waste' | 'equipment-idle' | 'energy-spike' | 'budget-exceed' | 'deadline-risk';

  @Prop({ required: true })
  severity: 'low' | 'medium' | 'high' | 'critical';

  @Prop({ required: true })
  title: string;

  @Prop({ required: true })
  message: string;

  @Prop({ default: false })
  isRead: boolean;

  @Prop({ default: 'pending' })
  status: 'pending' | 'resolved' | 'ignored';

  @Prop()
  resolvedAt: Date;

  @Prop({ type: Object, default: {} })
  metadata: Record<string, any>;

  // Timestamps (auto-generated by Mongoose)
  @Prop({ type: Date })
  createdAt: Date;

  @Prop({ type: Date })
  updatedAt: Date;
}

export const AlertSchema = SchemaFactory.createForClass(Alert);
