import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

@Schema({ timestamps: true })
export class Recommendation extends Document {
  @Prop()
  projectId?: string;

  @Prop()
  siteId?: string;

  @Prop({ default: 'site' })
  scope: 'project' | 'site';

  @Prop({ required: true })
  type:
    | 'energy'
    | 'workforce'
    | 'equipment'
    | 'scheduling'
    | 'environmental'
    | 'budget'
    | 'timeline'
    | 'task_distribution'
    | 'resource_allocation'
    | 'individual_task_management';

  @Prop({ required: true })
  title: string;

  @Prop({ required: true })
  description: string;

  @Prop({ default: 'pending' })
  status: 'pending' | 'approved' | 'rejected' | 'implemented';

  @Prop({ default: 0 })
  estimatedSavings: number; // €

  @Prop({ default: 0 })
  estimatedCO2Reduction: number; // kg

  @Prop({ default: 0 })
  priority: number; // 1-10

  @Prop({ default: 0 })
  confidenceScore: number; // 0-100

  @Prop({ type: [String], default: [] })
  actionItems: string[];

  @Prop({ type: Object, default: {} })
  metadata: Record<string, any>;

  @Prop()
  approvedAt: Date;

  @Prop()
  implementedAt: Date;

  // Timestamps (auto-generated by Mongoose)
  @Prop({ type: Date })
  createdAt: Date;

  @Prop({ type: Date })
  updatedAt: Date;
}
export const RecommendationSchema =
  SchemaFactory.createForClass(Recommendation); 
